### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by tamperplay** [HoshiKurama/TicketManager#11]
Mysql connection don't work.
AirPlane 1.17.1
Java 16
Plugin 5.2.4 for paper
`[17:25:40] [db-sql-netty-thread-1/ERROR]: [com.github.jasync.sql.db.mysql.MySQLConnection] <mysql-connection-1> Received an error message -> ErrorMessage(errorCode=1064, sqlState=#42000, errorMessage=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: com.github.jasync.sql.db.mysql.exceptions.MySQLException: Error 1064 - #42000 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.github.jasync.sql.db.mysql.MySQLConnection.onError(MySQLConnection.kt:189)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.kt:123)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:25:40] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[17:25:40] [ForkJoinPool.commonPool-worker-3/INFO]: 

[TicketManager] WARNING! An unexpected error has occurred!
     Exception:    MySQLException
     Information:  Error 1064 - #42000 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
=-=-=-=-=-=-=Modified Stacktrace:=-=-=-=-=-=-=`

**Comment by HoshiKurama** [comment]
Hey there! I’m currently travelling, but I’ll look into fixing the issue as soon as possible! In the mean-time, you’re welcome to use SQLite or the in-memory option as they can always be converted to MySQL later.

**Comment by tamperplay** [comment]
Ok, i will wait :)

**Comment by HoshiKurama** [comment]
In the mean time though, can you describe when this issue happens?

**Comment by tamperplay** [comment]
During the server startup, when it is almost already started

**Comment by HoshiKurama** [comment]
Issue narrowed down to when tables are being generated. Investigating now

**Comment by HoshiKurama** [comment]
Bug Fixed with version 5.2.5
