### ISSUE TITLE
Unsupported API version 1.18

### ISSUE THREAD

**Issue by magicmener** [HoshiKurama/TicketManager#15]
Hello, 
Server is 1.17.1

[Server thread/ERROR]: Could not load 'plugins/TicketManager-Spigot-7.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.18
	at org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:358) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-400]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-400]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-400]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-400]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by HoshiKurama** [comment]
Hi! TicketManager 7.0.1 requires Minecraft 1.18 or above.

**Comment by magicmener** [comment]
Which Version ist for 1.17.1

**Comment by HoshiKurama** [comment]
6.1.1 is the latest version for 1.17.1
