### ISSUE TITLE
This is not an error of MCCoroutine! See sub exception for details.

### ISSUE THREAD

**Issue by magicmener** [HoshiKurama/TicketManager#16]
Spigot 1.17.1 409
Ticketmanager TicketManager-Spigot-6.1.1.jar

[13:18:33] [Server thread/INFO]: [TicketManager] Loading 11 libraries... please wait
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlin/kotlin-stdlib/1.5.31/kotlin-stdlib-1.5.31.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/annotations/13.0/annotations-13.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlin/kotlin-stdlib-common/1.5.31/kotlin-stdlib-common-1.5.31.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/mysql/mysql-connector-java/8.0.25/mysql-connector-java-8.0.25.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/com/google/protobuf/protobuf-java/3.11.4/protobuf-java-3.11.4.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/xerial/sqlite-jdbc/3.36.0.2/sqlite-jdbc-3.36.0.2.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/com/github/jasync-sql/jasync-mysql/2.0.2/jasync-mysql-2.0.2.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/com/github/jasync-sql/jasync-pool/2.0.2/jasync-pool-2.0.2.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlin/kotlin-reflect/1.4.20/kotlin-reflect-1.4.20.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlinx/kotlinx-coroutines-jdk8/1.4.2/kotlinx-coroutines-jdk8-1.4.2.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.4.2/kotlinx-coroutines-core-1.4.2.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/com/github/jasync-sql/jasync-common/2.0.2/jasync-common-2.0.2.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.20/kotlin-stdlib-jdk8-1.4.20.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.20/kotlin-stdlib-jdk7-1.4.20.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/netty/netty-transport/4.1.49.Final/netty-transport-4.1.49.Final.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/netty/netty-common/4.1.49.Final/netty-common-4.1.49.Final.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/netty/netty-buffer/4.1.49.Final/netty-buffer-4.1.49.Final.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/netty/netty-resolver/4.1.49.Final/netty-resolver-4.1.49.Final.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/netty/netty-handler/4.1.49.Final/netty-handler-4.1.49.Final.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/netty/netty-codec/4.1.49.Final/netty-codec-4.1.49.Final.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/github/microutils/kotlin-logging/1.7.6/kotlin-logging-1.7.6.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/com/github/seratch/kotliquery/1.6.0/kotliquery-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/com/zaxxer/HikariCP/4.0.3/HikariCP-4.0.3.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.1/kotlinx-coroutines-core-jvm-1.5.1.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/joda-time/joda-time/2.10.13/joda-time-2.10.13.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/com/github/shynixn/mccoroutine/mccoroutine-bukkit-api/1.5.0/mccoroutine-bukkit-api-1.5.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/com/github/shynixn/mccoroutine/mccoroutine-bukkit-core/1.5.0/mccoroutine-bukkit-core-1.5.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlinx/kotlinx-serialization-core-jvm/1.3.0/kotlinx-serialization-core-jvm-1.3.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/dev/kord/kord-core/0.7.3/kord-core-0.7.3.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/dev/kord/kord-common/0.7.3/kord-common-0.7.3.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlinx/kotlinx-datetime-jvm/0.2.1/kotlinx-datetime-jvm-0.2.1.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/dev/kord/kord-rest/0.7.3/kord-rest-0.7.3.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-client-json-jvm/1.6.0/ktor-client-json-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-client-core-jvm/1.6.0/ktor-client-core-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-http-jvm/1.6.0/ktor-http-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-client-serialization-jvm/1.6.0/ktor-client-serialization-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-client-cio-jvm/1.6.0/ktor-client-cio-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-http-cio-jvm/1.6.0/ktor-http-cio-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-network-jvm/1.6.0/ktor-network-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-network-tls-jvm/1.6.0/ktor-network-tls-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-utils-jvm/1.6.0/ktor-utils-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-io-jvm/1.6.0/ktor-io-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/dev/kord/kord-gateway/0.7.3/kord-gateway-0.7.3.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/ktor/ktor-client-websockets-jvm/1.6.0/ktor-client-websockets-jvm-1.6.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/dev/kord/cache/cache-api/0.3.0/cache-api-0.3.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/dev/kord/cache/cache-map/0.3.0/cache-map-0.3.0.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlinx/kotlinx-serialization-json-jvm/1.2.1/kotlinx-serialization-json-jvm-1.2.1.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/org/jetbrains/kotlinx/atomicfu-jvm/0.16.1/atomicfu-jvm-0.16.1.jar
[13:18:34] [Server thread/INFO]: [TicketManager] Loaded library /home/minecraft/innenstadt/libraries/io/github/microutils/kotlin-logging-jvm/2.0.6/kotlin-logging-jvm-2.0.6.jar
...
[13:18:59] [Server thread/INFO]: [TicketManager] Loading TicketManager v6.1.1
...
[13:19:19] [Server thread/INFO]: [TicketManager] Enabling TicketManager v6.1.1
...
[13:19:42] [Craft Scheduler Thread - 7 - TicketManager/INFO]: [com.github.jasync.sql.db.util.NettyUtils] jasync available transport - native (epoll)
...
13:19:42] [Craft Scheduler Thread - 7 - TicketManager/INFO]: [com.github.jasync.sql.db.pool.ActorBasedObjectPool] registering pool for periodic connection tests com.github.jasync.sql.db.pool.ActorBasedObjectPool@7d15f978 - PoolConfiguration(maxObjects=1, maxIdle=60000, maxQueueSize=2147483647, validationInterval=5000, createTimeout=5000, testTimeout=5000, queryTimeout=null, coroutineDispatcher=AsyncCoroutineDispatcher@1f84cff2, maxObjectTtl=null)

...
[13:29:38] [Server thread/ERROR]: [TicketManager] This is not an error of MCCoroutine! See sub exception for details.
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.github.jasync.sql.db.general.ArrayRowData.get(ArrayRowData.kt:28) ~[?:?]
	at com.github.jasync.sql.db.RowData$DefaultImpls.getInt(RowData.kt:42) ~[?:?]
	at com.github.jasync.sql.db.general.ArrayRowData.getInt(ArrayRowData.kt:5) ~[?:?]
	at com.github.hoshikurama.ticketmanager.database.impl.MySQL.countOpenTickets(MySQL.kt:202) ~[TicketManager-Spigot-6.1.1.jar:?]
	at com.github.hoshikurama.ticketmanager.database.impl.MySQL$countOpenTickets$1.invokeSuspend(MySQL.kt) ~[TicketManager-Spigot-6.1.1.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by HoshiKurama** [comment]
Yeah, so version 6.1.1 had a bug where it used an incorrect index for the database, so it kinda messed up counting the number of open tickets. If I recall correctly, the issue might be limited to MySQL.

Sadly I do not support 6.1.1 anymore. You will need to either upgrade to a later version (and thus update your server to a later version of Minecraft, or you will need to use a different database type like SQLite mode or the memory mode. 

Of course you’re also welcome to compile TicketManager’s code yourself, but that also requires you know what you’re doing and how to set the project up yourself
