### ISSUE TITLE
Bug: An error occurred during command execution!

### ISSUE THREAD

**Issue by iCaitlyn** [HoshiKurama/TicketManager#18]
Several of the commands does not seem to work as intended...

Running on Paper 1.18.1, build 215, with Ticket Manager 8, fresh out of the box...
Config was untouched, TestingUser had ticketmanager.* permission node.

```
[15:25:26 INFO]: TestingUser issued server command: /ticket
[15:25:26 ERROR]: [TicketManager] An error occurred during command execution!
[15:25:30 INFO]: TestingUser issued server command: /ticket help
[15:25:30 ERROR]: [TicketManager] An error occurred during command execution!
[15:26:18 INFO]: TestingUser issued server command: /ticket version
[15:26:23 INFO]: TestingUser issued server command: /ticket help
[15:26:23 ERROR]: [TicketManager] An error occurred during command execution!
[15:26:35 INFO]: TestingUser issued server command: /ticket list
[15:26:38 INFO]: TestingUser issued server command: /ticket list
[15:26:48 INFO]: TestingUser issued server command: /ticket create Testing
[15:26:48 ERROR]: [TicketManager] An error occurred during command execution!
```

**Comment by iCaitlyn** [comment]
`/ticket version` produced the expected response, whereas `/ticket list` did not produce an error nor response (sort of also expected since there have not been any tickets yet)

**Comment by HoshiKurama** [comment]
If you go to config, can you enable full stacktrace mode? Try that and then send me the error

**Comment by iCaitlyn** [comment]
With `/ticket help`...

```
[17:00:36 ERROR]: [TicketManager] An error occurred during command execution!
[17:00:36 WARN]: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.TextDecorationAndState net.kyori.adventure.text.format.TextDecoration.withState(boolean)'
[17:00:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[17:00:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[17:00:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
[17:00:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[17:00:36 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[17:00:36 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[17:00:36 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[17:00:36 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[17:00:36 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[17:00:36 WARN]: Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.TextDecorationAndState net.kyori.adventure.text.format.TextDecoration.withState(boolean)'
[17:00:36 WARN]:        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.createNegated(DecorationTag.java:109)
[17:00:36 WARN]:        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$resolvers$2(DecorationTag.java:79)
[17:00:36 WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[17:00:36 WARN]:        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
[17:00:36 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[17:00:36 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[17:00:36 WARN]:        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
[17:00:36 WARN]:        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
[17:00:36 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[17:00:36 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[17:00:36 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[17:00:36 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[17:00:36 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[17:00:36 WARN]:        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$static$3(DecorationTag.java:92)
[17:00:36 WARN]:        at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1667)
[17:00:36 WARN]:        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
[17:00:36 WARN]:        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[17:00:36 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[17:00:36 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[17:00:36 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[17:00:36 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[17:00:36 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[17:00:36 WARN]:        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.<clinit>(DecorationTag.java:90)
[17:00:36 WARN]:        at net.kyori.adventure.text.minimessage.tag.standard.StandardTags.<clinit>(StandardTags.java:48)
[17:00:36 WARN]:        at net.kyori.adventure.text.minimessage.tag.resolver.TagResolver.standard(TagResolver.java:73)
[17:00:36 WARN]:        at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.lambda$static$0(MiniMessageImpl.java:57)
[17:00:36 WARN]:        at java.base/java.util.Optional.orElseGet(Optional.java:364)
[17:00:36 WARN]:        at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.<clinit>(MiniMessageImpl.java:57)
[17:00:36 WARN]:        at net.kyori.adventure.text.minimessage.MiniMessage.miniMessage(MiniMessage.java:53)
[17:00:36 WARN]:        at TicketManager-Paper-8.0.0.jar//com.github.hoshikurama.ticketmanager.misc.MiscellaneousKt.parseMiniMessage(Miscellaneous.kt:94)
[17:00:36 WARN]:        at TicketManager-Paper-8.0.0.jar//com.github.hoshikurama.ticketmanager.pipeline.CorePipeline$help$component$1.invoke(CorePipeline.kt:792)
[17:00:36 WARN]:        at TicketManager-Paper-8.0.0.jar//com.github.hoshikurama.ticketmanager.pipeline.CorePipeline$help$component$1.invoke(CorePipeline.kt:789)
[17:00:36 WARN]:        at TicketManager-Paper-8.0.0.jar//com.github.hoshikurama.ticketmanager.misc.kyoriComponentDSL.KyoriComponentDSLKt.buildComponent(KyoriComponentDSL.kt:8)
[17:00:36 WARN]:        at TicketManager-Paper-8.0.0.jar//com.github.hoshikurama.ticketmanager.pipeline.CorePipeline.help(CorePipeline.kt:789)
[17:00:36 WARN]:        at TicketManager-Paper-8.0.0.jar//com.github.hoshikurama.ticketmanager.pipeline.CorePipeline.executeCommand(CorePipeline.kt:289)
[17:00:36 WARN]:        at TicketManager-Paper-8.0.0.jar//com.github.hoshikurama.ticketmanager.pipeline.CorePipeline.executeLogic$lambda-2(CorePipeline.kt:68)
[17:00:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[17:00:36 WARN]:        ... 6 more
```

I'm guessing the issue is (after being able to see the stacktrace myself) is this version of the plugin most likely requires Adventure 4.10+, which only a certain build and up of Paper 1.18.2 supports

Interesting that it doesn't just crash at the start, though

**Comment by iCaitlyn** [comment]
"Easy" fix would be to indicate that it only supports Paper 1.18.2 and up, if that's the case

(Though we would still be remaining on 1.18.1 until WorldEdit updates to fully support 1.18.2)

**Comment by HoshiKurama** [comment]
I’ve updated the documentation to say that it only supports Paper 1.18.2 and up
