### ISSUE TITLE
TMMigrator failure

### ISSUE THREAD

**Issue by SlimeDog** [HoshiKurama/TicketManager#30]
Paper 1.20.1-170
TicketManager 10.0.1

Attempting to update from TM 9.0.1 with the TMMigrator.

On server start-up
```
[23:04:33] [Server thread/INFO]: [TMMigrator] Enabling TMMigrator v1.0
[23:04:33] [Server thread/INFO]: [TMMigrator] ============================
[23:04:33] [Server thread/INFO]: [TMMigrator] TicketManager Migration Tool
[23:04:33] [Server thread/INFO]: [TMMigrator]           V9 -> V10
[23:04:33] [Server thread/INFO]: [TMMigrator] ============================
[23:04:33] [Server thread/INFO]: [TMMigrator] Searching for previous attempts...
[23:04:33] [Server thread/INFO]: [TMMigrator] No previous attempts detected. Writing addon config files...
[23:04:33] [Server thread/ERROR]: Error occurred while enabling TMMigrator v1.0 (Is it up to date?)
java.lang.NullPointerException: null
        at com.github.hoshikurama.tmmigrator.UpdaterKt.migrateDiscordConfigs(Updater.kt:115) ~[TM_Migrator-V9-V10.jar:?]
        at com.github.hoshikurama.tmmigrator.MigrationTool$onEnable$1.invokeSuspend(MigrationTool.kt:54) ~[TM_Migrator-V9-V10.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[?:?]
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) ~[?:?]
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[?:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[?:?]
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[?:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[?:?]
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[?:?]
        at com.github.hoshikurama.tmmigrator.MigrationTool.onEnable(MigrationTool.kt:28) ~[TM_Migrator-V9-V10.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-170]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-170]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-170]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-170]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-170]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-170]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[23:04:33] [Server thread/INFO]: [TMMigrator] Disabling TMMigrator v1.0
```
and commands are locked.

**Comment by HoshiKurama** [comment]
Should be resolved.

**Comment by SlimeDog** [comment]
Not reattempted. I installed anew (see #31).
