### ISSUE TITLE
Errors on new installation

### ISSUE THREAD

**Issue by SlimeDog** [HoshiKurama/TicketManager#31]
Paper 1.20.1-170
TicketManager 10.0.1

New installation (ie., plugins/TicketManager does not exist).

On server startup:
```
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]: java.util.concurrent.CompletionException: com.github.hoshikurama.ticketmanager.shaded.h2.jdbc.JdbcSQLSyntaxErrorException: (Message 42S02 not found); SQL statement:
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]: SELECT * FROM TicketManager_V8_Tickets; [42102-220]
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]: Caused by: com.github.hoshikurama.ticketmanager.shaded.h2.jdbc.JdbcSQLSyntaxErrorException: (Message 42S02 not found); SQL statement:
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]: SELECT * FROM TicketManager_V8_Tickets; [42102-220]
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.message.DbException.getJdbcSQLException(DbException.java:514)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.message.DbException.getJdbcSQLException(DbException.java:489)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.message.DbException.get(DbException.java:223)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.message.DbException.get(DbException.java:199)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8561)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8532)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.readTableOrView(Parser.java:8521)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.readTablePrimary(Parser.java:1911)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.readTableReference(Parser.java:2391)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parseSelectFromPart(Parser.java:2844)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parseSelect(Parser.java:2950)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parseQueryPrimary(Parser.java:2834)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parseQueryTerm(Parser.java:2690)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parseQueryExpressionBody(Parser.java:2669)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2662)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parseQueryExpression(Parser.java:2655)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parseQuery(Parser.java:2624)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parsePrepared(Parser.java:732)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parse(Parser.java:697)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.parse(Parser.java:669)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.command.Parser.prepareCommand(Parser.java:577)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:634)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:557)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.kotliquery.Session.createPreparedStatement(Session.kt:109)
[23:13:31] [ForkJoinPool.commonPool-worker-3/WARN]:     at TicketManager-10.0.1.jar//com.github.hoshikurama.ticketmanager.shaded.kotliquery.Session.rows(Session.kt:120)
```
and commands are locked.

**Comment by HoshiKurama** [comment]
Seems like my Git history messed up and merged the wrong file in, so the statements are still referring to v8 tables. I will fix that later today.

**Comment by SlimeDog** [comment]
Testing...

**Comment by HoshiKurama** [comment]
Resolved

**Comment by SlimeDog** [comment]
Paper 1.20.1-170
TM 10.0.2

On server startup, TM loaded and initialized successfully.
