### ISSUE TITLE
1.21.4 support

### ISSUE THREAD

**Issue by joshwenke** [HoshiKurama/TicketManager#39]
When will this plugin be updated for 1.21.4?

[K[31;1m[13:21:48 ERROR]: [TicketManager] Error initializing plugin 'TMSE-Paper-11.1.5.jar' in folder 'plugins' (Is it up to date?)
com.github.hoshikurama.ticketmanager.shaded.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.21.4
        at TMSE-Paper-11.1.5.jar/com.github.hoshikurama.ticketmanager.shaded.commandapi.CommandAPIVersionHandler.getPlatform(CommandAPIVersionHandler.java:90) ~[TMSE-Paper-11.1.5.jar:?]
        at TMSE-Paper-11.1.5.jar/com.github.hoshikurama.ticketmanager.shaded.commandapi.CommandAPI.onLoad(CommandAPI.java:112) ~[TMSE-Paper-11.1.5.jar:?]
        at TMSE-Paper-11.1.5.jar/com.github.hoshikurama.ticketmanager.paper.PaperPlugin.onLoad(PaperPlugin.kt:30) ~[TMSE-Paper-11.1.5.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:575) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:332) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by HoshiKurama** [comment]
Good morning! Sorry about this! I didn't know 1.21.4 would release so soon after 1.21.3! I'll update the code now and push a new update

**Comment by HoshiKurama** [comment]
Update posted!
